# This is a basic workflow to help you get started with Actions

name: Run Playwright tests

on:
  push:
    branches: [ main ]
  schedule:
    - cron: 0 22 1 1-12 *
  workflow_dispatch:

jobs:
  run-blog-tests:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        name: Playwright - Install Node
        with:
          node-version: '14'
          
      - name: Playwright - Install OS dependencies
        run: npx playwright install-deps chromium
        
      - name: Playwright - Run tests on blog
        env:
          filenamewordmatch: 'blog'
        run: npx playwright test --browser chromium -g '${{ env.filenamewordmatch }}' --retries 1 --max-failures 5 --output test-results 
